### ISSUE TITLE
[Bug]: Simple Scene Hands aren't moving

### ISSUE THREAD

**Issue by sinoth** [leetvr/hotham#175]
### What happened?

The hands are stuck to the floor and don't seem to be receiving position updates from the controllers.

### Version

latest

### In which Hotham component are you seeing the problem on?

Example

### What VR System are you seeing the problem on?

Quest-2

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by kanerogers** [comment]
Hey, @sinoth! Thanks so much for creating this one.

As discussed last Friday, I think this is a fantastic issue for you to jump on to, as it'll require you to jump into the bowels of Hotham to debug it.

There's a 3 step process to updating the position of the hands:

1. Fetching the position from OpenXR
2. Setting the position of the `RigidBody` of the entity (eg. _NOT_ the `Transform`)
3. Updating the `Transform`' of the entity

This bug could be sneaking into any one of those places! So, a quick sanity check would be to make sure:

1. Is the `hands` system being called?
2. Is the `update_rigid_body_transforms` system being called?

If they both are, then we've got a bug.

Debugging could take the form of adding a `Panel` to the scene (see `CrabSaber` for an example of how `Panel`s work) that displays:

1. Where `OpenXR` thinks the Hands are (check the `hands` system for how to do that)
2. What's the position of the `RigidBody`?
3. What's the position of the `Transform`?

If any one of those 3 values is _not_ in sync..

![image](https://user-images.githubusercontent.com/2022375/160303929-0177b9e1-1693-45ec-af65-e327ac530e1b.png)

**Comment by sinoth** [comment]
Thanks for the explanation! It helped wade through the hands system.

I can't reproduce this bug. I think perhaps my Quest was in a bad state and after a reboot the hands work fine.

Potentially related to #176 

Closing this unless anyone else can reproduce.
