### ISSUE TITLE
[Bug]: Simple scene hands don't move if only one controller is connected

### ISSUE THREAD

**Issue by sinoth** [leetvr/hotham#179]
### What happened?

Both hands seem stuck to the floor and do not receive position updates if only one Touch controller is connected. Once both are connected, the hands spring to life.

### Version

0.1.1 (Default)

### In which Hotham component are you seeing the problem on?

Example

### What VR System are you seeing the problem on?

Quest-2

### What OS are you seeing the problem on?

Windows

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kanerogers** [comment]
I've checked simple app and have been able to reproduce the bug. 👌🏻
