### ISSUE TITLE
[Feature] Split Panel up so that applications can do their own rendering into Panels

### ISSUE THREAD

**Issue by jmgao** [leetvr/hotham#187]
I've been told by one of the graphics wizards at oculus that the ideal way to render text on Quest is to use [composition layers](https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html#composition-layer-types), which avoids some error from distortion correction, or something along those lines. However, it seems like Hololens [specifically recommends against it](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/native/openxr-best-practices#avoid-quad-layers), and the simulator might not support it? This seems like something that it'd be nice for the engine to abstract over and handle for the application, and I think the first step is to split up Panel into the part that provides a texture to draw into and does raw input handling, and the part that uses egui to draw stuff, and passes inputs into egui.

**Comment by kanerogers** [comment]
This was closed in #189
