### ISSUE TITLE
[Bug]: get_cursor_location_for_pane seems wrong for the side panel in crab saber

### ISSUE THREAD

**Issue by jmgao** [leetvr/hotham#192]
### What happened?

It looks like the x coordinate of the cursor location on the side panel in crab saber is wrong, with a value along the lines of `(correct_x + width)/2`. Not sure yet if this is because it's not centered, or because it's not square, or because of something weirder.

### Version

latest

### In which Hotham component are you seeing the problem on?

Core

### What VR System are you seeing the problem on?

Quest-2

**Comment by kanerogers** [comment]
I believe this has been fixed
