### ISSUE TITLE
[Bug] Hands animation no longer working

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#234]
## Background
After the upgrade of the glTF importer and the new rendering backend, the hands animation is no longer working. This is somewhat understandable as the way hands were being animated was a big hack.

glTF animation is [well defined](https://www.khronos.org/registry/glTF/specs/2.0/glTF-2.0.html#animations), but for some reason when exporting the default Oculus hands from Unity, the animations are completely mangled: instead of giving us _keyframes_ between two states (hand open and hand closed) we get two _animations_, each with a **single** keyframe. We work around this by just creating a single animation and use each state (open and closed) as a keyframe.

## TODO
- [ ] Should we just get better models with correct animations?

**Comment by kanerogers** [comment]
@sinoth as discussed last week; what are your thoughts?

**Comment by kanerogers** [comment]
> > @sinoth as discussed last week; what are your thoughts?
> 
> I don't have any quality hands tucked away. This is something I would normally throw money at, but licensing hands to include in an engine might be a headache. I'm tempted to hack the Oculus hands to work as they are nicely stylized and great for prototyping. I'll try to find a different version of them or maybe fix the issue in Blender.

Mm, that's a fair point! Maybe fixing them in Blender is a good idea; I hadn't tried that previously as my animation skills are pretty lacking!

**Comment by rasmusgo** [comment]
I think the two different animations are there because they represent non-linear actions. This makes sense if you consider more movements than only open and closed (eg. point with index finger).

This video was helpful for me to understand how non-linear animations work in Blender: https://youtu.be/tAo7HxxxA08
