### ISSUE TITLE
Not everything should be grabbable by the hands

### ISSUE THREAD

**Issue by ickk** [leetvr/hotham#247]
Pretty sure this is the cause of a crash when the hands get close together, but it's also just a problem if the hands happen to be on top of multiple entities with colliders when gripping - as whichever entity happens to be seen by the grabbing system first will get grabbed, even if it's not actually intended to be interacted with.

Solution: Add a `Grabbable` marker component

**Comment by kanerogers** [comment]
## NICE CATCH

![giphy](https://user-images.githubusercontent.com/2022375/178199341-7e6d914e-2392-4697-bfb2-82171dc4290b.gif)
