### ISSUE TITLE
[Rendering] Fix frustum culling

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#275]
At present our frustum culling is both slow and incorrect.

An optimisation was made by @kanerogers to create a virtual frustum incorporating both cameras, but this has not proven to be correct. In addition, the underlying isVisible function in the compute shader is extremely expensive, and should, if possible, be reduced to a plane intersection check.

**Comment by Ralith** [comment]
I'm assuming that #280 addressed the correctness issues. The current code looks reasonable to me in that respect, though I haven't independently audited the math used to extract clipping planes. However, one serious design issue remains:

https://github.com/leetvr/hotham/blob/c3fc0142a9e6d1f9a68d9cbe2ffd8e9def27c19c/hotham/src/resources/render_context.rs#L284-L287

This forces a full pipeline stall and host round-trip between culling and whatever operations follow (presumably, drawing). It should be replaced with appropriate pipeline barriers.

**Comment by kanerogers** [comment]
Thanks for looking into this!

re: the hard wait on the Fence, how would we ensure the dispatch is complete when the CPU then reads the cull buffer? 

Noting that we are not doing multiDrawIndirect; we are simply iterating through the results of the cull buffer and guiding up our draw commands CPU side. Previously we simply used barriers and drawIndirect, which though technically correct, has serious implementation issues on the Adreno 650 hardware we're targeting.

**Comment by Ralith** [comment]
Ah, I didn't realize you had resorted to reading back the results on the CPU! In that case it might be better to do the culling on the CPU exclusively rather than synchronously shuffling data back and forth, though it's hard to say for sure without profiling and/or benchmarking on the target hardware with representative scenes. Another option is conditional rendering, but that doesn't seem to be supported on the Quest 2.

Is the vendor working on fixing their bugs? Might make sense to hold off on further iteration regardless if a fix is in flight.

**Comment by kanerogers** [comment]
I have thought about doing everything on the CPU, but the overhead for CPU
<> GPU seems fairly minimal from my profiling (remembering that we’ve got
unified coherent memory). At the very least, the cost of parallelism should
be in our favour for any real world number of objects.

re: vendor bugs it doesn’t seem to be so much of a bug as a design flaw.
The entire Adreno series seems to not have good support for drawIndirect,
and speaking with Meta and other engine folks (eg. Godot), the solution is
just to not even bother. We can get pretty good results with CPU batching
and GPU instancing, so I’m reasonably happy with this architecture for now,
even though a purely GPU driven renderer would be much more satisfying.

Meta has been (understandably) tight lipped about the hardware for their
upcoming high end headset, but  think we can assume it’ll probably still be
Qualcomm hardware. In any event, it took 5 minutes to implement  the
fence/drawInstanced change, I’d imagine it would take a trivial amount of
time to add an optional path for drawIndirect if we get Vulkan hardware
that properly supports it.

**Comment by Ralith** [comment]
Sounds like this issue is settled for now, then!
