### ISSUE TITLE
[Bug] Updating transform of skinned joints on quest 2 is broken.. somehow

### ISSUE THREAD

**Issue by ickk** [leetvr/hotham#294]
There is validation that skinning *appears* to work on [ickk/skinning-sanity-test](https://github.com/leetvr/hotham/tree/ickk/skinning-sanity-test), however there in certain circumstances this seems to fail. 

Everything seems to work fine in the simulator, but it fails on device.

This could be related to #234.

Reproduction is available on https://github.com/leetvr/the_station/issues/47

Exact cause remains elusive

**Comment by kanerogers** [comment]
@ickk I have a strange feeling this may be related to re-ordering of systems. Will investigate

**Comment by kanerogers** [comment]
Fixed in #340
