### ISSUE TITLE
[Rendering] Objects without materials do not render correctly

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#302]
## Background
![image](https://user-images.githubusercontent.com/2022375/182557922-7eb1406d-a76e-4cfb-b8f0-81d4264e5138.png)
Space station look like asteroid. But _space station not asteroid_

## TODO
- [x] RenderDoc to glory

**Comment by ickk** [comment]
![image](https://user-images.githubusercontent.com/17050131/182562005-ae095d19-36e0-42d8-9e05-36a73f6ea28a.png)

**Comment by kanerogers** [comment]
> ![image](https://user-images.githubusercontent.com/17050131/182562005-ae095d19-36e0-42d8-9e05-36a73f6ea28a.png)

OK you got me, what's the reference? :P

**Comment by ickk** [comment]
https://youtu.be/d_XVVCVHGlQ?t=9

**Comment by kanerogers** [comment]
Nice 😆

**Comment by kanerogers** [comment]
Tracked it down to issues with objects without materials
