### ISSUE TITLE
[Rendering] Culling does not appear to be correct

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#303]
## Background
In this screenshot, the camera is facing away from the asteroid:

![image](https://user-images.githubusercontent.com/2022375/182564270-6a22c3ae-d730-4570-89a9-a796292f8dfa.png)

However, its draw call can be seen in RenderDoc:

![image](https://user-images.githubusercontent.com/2022375/182564400-269301c2-78be-407c-848d-e291b415c48a.png)

_But_, `EID` 37 shows that about half the cubes have been culled (eg. the draw command is `vkCmdDrawIndexed(36, 655)`). Given that there are a total of 1,653 cubes, it would follow that these cubes have been culled correctly.

**Comment by rasmusgo** [comment]
I think the clip planes broke in https://github.com/leetvr/hotham/pull/298 when the projection matrix changed. I pushed a potential fix in the branch kanerogers/issue303.
