### ISSUE TITLE
Installation instructions unclear for me

### ISSUE THREAD

**Issue by atrefonas** [leetvr/hotham#331]
## Description
I wanted to play around with this on Windows with my Oculus, but I can't understand all the installation instructions in https://github.com/leetvr/hotham/wiki/Getting-started.

- `adb devices` doesn't work, and don't understand which installation it would come from.
```
PS C:\Windows\system32> adb devices
adb : The term 'adb' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
```
- `We use [shaderc](https://github.com/google/shaderc) to compile our shaders at build time, so you'll need to make sure it's installed and available on your PATH.`

How do I install shaderc? On their Github it isn't clear to me. I downloaded the binary from one of their links but it's a zip without an installer and I don't know what to do afterwards

**Comment by kanerogers** [comment]
Hey there @atrefonas! I'm so sorry you had such a bad onboarding experience to Hotham. We're doing our best to keep the Wiki up-to-date, but are totally aware that there's many confusing - and sometimes contradictory - steps on that list.

I'll try to reply to each of these points one by one!

> adb devices doesn't work, and don't understand which installation it would come from

Good pickup! `adb` should have been part of your Android SDK installation. It should be wherever you installed the SDK - Google has [some documentation](https://developer.android.com/studio/command-line) that may help.

> We use [shaderc](https://github.com/google/shaderc) to compile our shaders at build time, so you'll need to make sure it's installed and available on your PATH.

Ah that's a very good point. You're probably better off installing [the Vulkan SDK](https://www.lunarg.com/vulkan-sdk/) to get `shaderc`, so if that works better for you let me know and we'll update the instructions accordingly.

If there's anything else you get stuck with - and given how complicated this all is, that's very likely - please drop into our Discord! There's lots of friendly, helpful people there who can give you a hand.

Thanks again for taking a look at Hotham!

**Comment by kanerogers** [comment]
Closing this one off due to inactivity. We definitely need to work on our docs more; in the meantime [Discord](https://discord.gg/SZEZUX6ZsQ) is the best way to get suport.
