### ISSUE TITLE
[Simulator] Add no-op for haptics

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#350]
## Background
Attempting to call `hotham::schedule_functions::apply_haptic_feedback::apply_haptic_feedback` in the simulator results in a _very bad time_.

## Solution
1. Find the corresponding openxr API call used in `hotham::schedule_functions::apply_haptic_feedback::apply_haptic_feedback`
2. Add a branch to `get_instance_proc_addr` in `simulator/lib.rs` for that API call
3. Add a corresponding no-op function in `simulator.rs`

**Comment by MultisampledNight** [comment]
I'd tackle this now.
