### ISSUE TITLE
[Maintenance] Refactor `physics_system`

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#366]
## Background
At the moment, our integration with Rapier is a little loose. Developers need to do a lot of work to get their game simulations synchronized with the physics simulation. Let's try and fix that.

## Design
Almost every problem in game engine design is some sort of synchronization problem. The easiest way to simplify synchronization problems is to define the source of truth, ie. "who is authoritative over this data".

What data do we want to synchronize between the physics simulation and the game simulation? Mostly, it's just global transforms (ie. where is this entity located in global space).

At a high level, there's 3 ways an entity might want to have its global transform synchronized with the physics simulation:

1. No synchronization at all
1. Physics authoritative (ie. after the simulations have synchronized, `GlobalTransform` will be equal to the position in the physics simulation)
    - eg. objects whose movement we want modelled in some sort of physical way (ie. by simulating gravity or velocity etc).
1. Game authoritative (ie. after the simulations have synchronized, the position in the physics simulation will be equal to `GlobalTransform`).
    - eg. things like colliders which don't have any dynamics but still need a position in the physics simulation, or kinematic objects in the physics simulation

A simple `PhysicsControlled` tag component could be able to indicate to the relevant system what should be considered authoritative. It is still up to the game developer to add this tag to the right kinds of entities, and ensure their physics simulation representations are configured correctly.

## TODO
- [x] Create `PhysicsControlled` component
- [x] Handle case 1
- [x] Handle case 2

**Comment by rasmusgo** [comment]
I think it could make sense to use the parenting hierarchy for this. The parent could be an enum to None, an entity, or a rigid body. The rigid body parent would replace the rigid body component with the added advantage of only allowing rigid bodies at the root of the hierarchy.

The game authoritative case would be handled by setting the transformation of the kinematic bodies explicitly.
