### ISSUE TITLE
[Maintenance] Replace `nalgebra` with `glam`

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#372]
## Background
**[Nalgebra, I love you, but you're bringing me down](https://www.youtube.com/watch?v=-eohHwsplvY)**.

`nalgebra` is a great maths library. It does *lots* of cool stuff. 

_But,_ it's a pain in the fucking arse in most cases. So many things that are otherwise simple in other Maths libraries are just mind-bendingly complicated in `nalgebra`. Its errors are indecipherable, its documentation is a maze of darkness and it uses so many traits that it [gets specifically called out in the `cargo` docs for its heavy use of generics](https://doc.rust-lang.org/cargo/reference/profiles.html#overrides-and-generics).

So, let's [hurl it into the sun](https://www.wired.com/2017/03/lets-physics-knocking-asteroid-sun/) and replace it with `glam`.

## TODO
- [x] How do we keep `rapier` and still have `nalgebra`?
- [ ] Do it

**Comment by rasmusgo** [comment]
I beg you not to do this

**Comment by rasmusgo** [comment]
At least use https://docs.rs/nalgebra-glm/latest/nalgebra_glm/ instead
