### ISSUE TITLE
[Rendering] Support loading tangents from assets again

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#393]
## Background
We've gone back and forth on tangents a couple times; @rasmusgo found that computing tangents on the fly is actually quicker, so we've implemented this in https://github.com/leetvr/hotham/pull/342

*However*, some models simply require tangents that were calculated offline, eg.

![image](https://user-images.githubusercontent.com/2022375/197694207-1f4c9a28-00dd-4b27-a04e-ed8812ff9bad.png)
![image](https://user-images.githubusercontent.com/2022375/197695456-2e6c9daa-040a-4831-825b-3a1d185ede21.png)

**Comment by rasmusgo** [comment]
Geez, you startled me! 😅
