### ISSUE TITLE
Switch to `nalgebra` everywhere

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#46]
## Description
`cgmath` has been great to get us started but it's starting to produce a bit of friction.

## TODO
- [ ] Remove `cgmath` dependency from `toml`
- [ ] Fix all the things that break

**Comment by Ralith** [comment]
If you want physics, you'll probably use rapier, which means you'll have nalgebra in your dependency tree regardless. It's very powerful but some people find the verbose/obscure type errors from the highly generic stuff offputting, and you might get better compile times if you touch it as little as possible. On the whole I like it, personally.

**Comment by kanerogers** [comment]
> If you want physics, you'll probably use rapier, which means you'll have nalgebra in your dependency tree regardless. It's very powerful but some people find the verbose/obscure type errors from the highly generic stuff offputting, and you might get better compile times if you touch it as little as possible. On the whole I like it, personally.

Good point re: `rapier`. We're already using it and I'm having to do conversions between `cgmath` and `nalgebra` in places anyway which is a bit gross. I have to admit I'd prefer something a bit less generic, but there's (probably) a bigger performance penalty switching around between libraries than just sticking with `nalgebra`.

**Comment by Ralith** [comment]
> there's (probably) a bigger performance penalty switching around between libraries than just sticking with nalgebra.

I'm actually skeptical of that. The layouts are identical, so LLVM will see that it's a simple memcpy, and it'll bake down to no different than a regular `Copy`. Might matter if it prevents you from passing matrices by reference in a major way, but otherwise it's probably insignificant. Of course, the cognitive overhead of switching between them all the time is its own thing.

**Comment by kanerogers** [comment]
There are a couple places where we pass vectors/matrices by reference so it
does force us to do unnecessary copies (or an evil mem::transmute), but
yes, the cognitive overhead is probably the real problem. :)
