### ISSUE TITLE
Fix logging

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#55]
## Description
Everyone loves logging!

## TODO
- [x] See which logging library is fashionable these days
- [x] Investigate `tracing`
- [ ] Implement it

**Comment by Ralith** [comment]
I'm a big fan of `tracing` due to how easy it makes it to establish context for log messages. Helps reduce scrolling around in a big dump trying to correlate things, and with the tracing-error crate you can incorporate that same context into error messages.

**Comment by kanerogers** [comment]
> I'm a big fan of `tracing` due to how easy it makes it to establish context for log messages. Helps reduce scrolling around in a big dump trying to correlate things, and with the tracing-error crate you can incorporate that same context into error messages.

Oooh! I'll take a look! Thanks @Ralith 😄

**Comment by kanerogers** [comment]
`tracing` looks excellent! I think for 0.1 scope we'll just use `tracing` as a simple facade over `log`, but integration with `tracy` looks amazing.

**Comment by kanerogers** [comment]
Not high priority; we can always come back to this.
