### ISSUE TITLE
Investigate `hecs` again

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#60]
## Description
Using `legion`, there's been a lot to love, but there's also been some pretty annoying issues.

- `system` macros aren't picked up by `rust-analyzer`
- There's a lot of nice sugar around `legion` but a lot of it isn't well documented. `hecs` is a bit more barebones.
- `legion` doesn't look to be actively maintained and I *DO NOT* want to be maintaining a fork of an ECS - I'm just not smart enough for that. :P

**Comment by davidkuhta** [comment]
Using hecs <3
