### ISSUE TITLE
Move `simulator` to its own repository

### ISSUE THREAD

**Issue by kanerogers** [leetvr/hotham#76]

**Comment by kanerogers** [comment]
I went with a monorepo to begin with, mostly because I'm lazy, rather than any focussed direction. I know bevy for instance is also a monorepo. 

@ralith @wbrickner  what are your views on repository structures?

**Comment by Ralith** [comment]
Highly recommend using a single repository containing a cargo workspace for closely related projects, i.e. those which tend to have interdependent changes.

**Comment by kanerogers** [comment]
Sold! Closing this issue then.
